# Generated by Django 4.2.5 on 2023-10-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicuser', '0002_personalizeddata1_founders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalizeddata1',
            name='founders',
        ),
        migrations.AddField(
            model_name='personalizeddata1',
            name='founders',
            field=models.JSONField(default=list),
        ),
    ]
