# Generated by Django 4.2.5 on 2023-10-21 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicuser', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalizeddata1',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='publicuser.customuser'),
        ),
    ]
