# Generated by Django 4.2.5 on 2024-02-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Username',
            field=models.CharField(max_length=20),
        ),
    ]
