# Generated by Django 4.2.5 on 2023-10-25 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('admin', 'Admin User'), ('FOUNDERS', 'FOUNDERS'), ('INVESTORS', 'INVESTORS')], default='regular', max_length=10),
        ),
    ]
