# Generated by Django 4.2.5 on 2023-10-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customUser1',
        ),
    ]
