# Generated by Django 4.2.4 on 2023-10-17 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drink',
            new_name='Authentication',
        ),
    ]
