# Generated by Django 4.2.5 on 2023-10-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0002_rename_drink_authentication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='Email',
            field=models.CharField(max_length=40),
        ),
    ]
