# Generated by Django 4.2.5 on 2023-10-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.CharField(default='Jaadu', max_length=255, null=True),
        ),
    ]
