# Generated by Django 4.2.5 on 2023-10-27 02:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0004_notification_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizeddata',
            name='investors',
            field=models.ManyToManyField(blank=True, related_name='investor_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
