# Generated by Django 4.2.5 on 2023-10-17 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0004_customuser_delete_authentication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
