# Generated by Django 4.2.5 on 2023-10-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0005_personalizeddata_investors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalizeddata',
            name='investors',
        ),
        migrations.AddField(
            model_name='personalizeddata',
            name='investors',
            field=models.JSONField(default=list),
        ),
    ]
