# Generated by Django 4.2.5 on 2023-10-17 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
