# Generated by Django 4.2.5 on 2023-10-28 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0007_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
