# Generated by Django 4.2.5 on 2023-10-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0008_events_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.CharField(max_length=255),
        ),
    ]
