# Generated by Django 4.2.5 on 2023-10-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0009_alter_events_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='Shivanshu Ranjan', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phonenumber',
            field=models.IntegerField(default=8210892090, max_length=12),
        ),
    ]
