# Generated by Django 4.2.5 on 2023-10-21 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0009_question_personalizeddata_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalizeddata',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth1.question'),
        ),
    ]
