# Generated by Django 4.2.5 on 2023-10-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0010_customuser_name_customuser_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phonenumber',
            field=models.IntegerField(default=8210892090),
        ),
    ]
