# Generated by Django 4.2.5 on 2023-10-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0011_alter_customuser_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='personalizeddata',
            name='name',
            field=models.CharField(default='Shivanshu Ranjan', max_length=20),
        ),
        migrations.AddField(
            model_name='personalizeddata',
            name='phonenumber',
            field=models.IntegerField(default=8210892090),
        ),
    ]
