# Generated by Django 4.2.5 on 2023-10-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0012_remove_customuser_name_remove_customuser_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalizeddata',
            name='phonenumber',
            field=models.CharField(default=8210892090, max_length=12),
        ),
    ]
