# Generated by Django 4.2.5 on 2024-02-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0014_alter_personalizeddata_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalizeddata',
            name='phonenumber',
            field=models.CharField(default='8210892', max_length=12),
        ),
    ]
